/**
 * NexoraOS™ — Shared Constants
 * Table whitelist, policy domain mapping, and helper utilities
 */

export const TABLE_WHITELIST = [
  'investment_projects',
  'investment_returns_history',
  'strategic_plans',
  'strategic_goals',
  'swot_analysis',
  'strategic_kpis',
  'strategic_initiatives',
  'code_categories',
  'password_resets',
  'organizations',
  'user_org_memberships',
  'user_sessions',
  'login_attempts',
  'two_factor_auth',
  'users',
  'code_items',
  'fiscal_years',
  'fiscal_periods',
  'currencies',
  'exchange_rates',
  'financial_accounts',
  'procurement_tenders',
  'chart_of_accounts',
  'party_roles',
  'party_relationships',
  'party_documents',
  'party_assessments',
  'party_visits',
  'item_units',
  'party_feedback',
  'project_phase_transitions',
  'project_funding_links',
  'project_indicators',
  'indicator_measurements',
  'activity_beneficiaries',
  'activity_volunteers',
  'warehouses',
  'inventory_items',
  'inventory',
  'transaction_workflows',
  'recurring_transactions',
  'budget_revisions',
  'investment_transactions',
  'donor_restrictions',
  'beneficiary_service_log',
  'stock_count_sessions',
  'investment_assets',
  'workflow_definitions',
  'transaction_lines',
  'notification_templates',
  'alert_rules',
  'sms_logs',
  'email_logs',
  'field_evidence',
  'attachments',
  'audit_logs',
  'roles',
  'role_permissions',
  'permissions',
  'user_roles',
  'organization_settings',
  'session_activities',
  'email_verifications',
  'ip_rules',
  'api_keys',
  'geographic_areas',
  'service_points',
  'compliance_logs',
  'data_exports',
  'contracts',
  'training_programs',
  'analytics_metrics',
  'training_participants',
  'reports',
  'system_settings',
  'backups',
  'integration_logs',
  'scheduled_tasks',
  'incidents',
  'document_versions',
  'risk_assessments',
  'stock_count_lines',
  'approval_delegations',
  'custom_field_definitions',
  'custom_field_values',
  'tags',
  'entity_tags',
  'user_favorites',
  'user_recent_items',
  'system_health_checks',
  'approval_requests',
  'system_audit_trail',
  'party_representatives',
  'user_activity_logs',
  'party_intermediaries',
  'approval_steps',
  'inventory_transfers',
  'inventory_transfer_lines',
  'inventory_issues',
  'budget_commitment_utilizations',
  'inventory_issue_lines',
  'asset_maintenance',
  'budget_commitments',
  'budget_variance_analysis',
  'beneficiary_assessments',
  'beneficiary_indicators',
  'smart_alert_templates',
  'config_changes_log',
  'smart_alert_executions',
  'dashboards',
  'dashboard_widgets',
  'webhooks',
  'system_performance_metrics',
  'webhook_executions',
  'data_quality_rules',
  'password_policies',
  'data_quality_issues',
  'security_events',
  'bank_reconciliations',
  'bank_reconciliation_items',
  'installments',
  'knowledge_articles',
  'cost_centers',
  'v_beneficiary_status_report',
  'allowances',
  'database_records_summary',
  'v_database_summary',
  'v_monthly_donations_report',
  'v_monthly_payroll_report',
  'v_salary_by_department',
  'v_bonuses_incentives_report',
  'v_financial_by_branches',
  'v_fixed_assets_comprehensive_report',
  'v_beneficiary_registration_report',
  'v_data_quality_comprehensive_report',
  'v_endowment_returns_report',
  'v_resource_usage_report',
  'v_login_attempts_report',
  'v_security_audit_advanced',
  'v_system_logs_report',
  'v_project_dashboard',
  'v_program_dashboard',
  'v_executive_dashboard',
  'v_activity_dashboard',
  'v_beneficiary_geographic_report',
  'v_financial_transactions_report',
  'v_cash_flow_report',
  'v_sponsorship_report',
  'v_project_comprehensive_report',
  'v_task_advanced_dashboard',
  'v_program_performance_analysis',
  'v_project_risk_analysis',
  'v_activity_performance_analysis',
  'v_task_performance_analysis',
  'v_advanced_business_kpis',
  'v_program_beneficiary_impact',
  'v_resource_allocation_report',
  'v_financial_compliance_report',
  'v_operational_costs_report',
  'v_operational_revenue_report',
  'v_employees_report',
  'v_executive_budget_report',
  'v_activity_implementation_report',
  'v_activity_attendance_report',
  'v_current_inventory_report',
  'v_risk_comprehensive_report',
  'v_incidents_report',
  'v_donor_report',
  'v_payments_collections_analysis',
  'v_system_performance_report',
  'payroll_periods',
  'attendance_records',
  'salary_components',
  'employee_salary_structures',
  'leave_requests',
  'work_sessions',
  'field_tasks',
  'activity_attendance',
  'data_change_log',
  'approval_matrix',
  'approval_history',
  'v_field_tasks_report',
  'v_attendance_report',
  'v_work_sessions_report',
  'employee_bank_accounts',
  'v_migration_final_summary',
  'payroll_records',
  'migration_staging',
  'migration_log',
  'v_activities_by_project',
  'v_employee_payroll_detailed',
  'v_payroll_summary_detailed',
  'v_migration_status',
  'v_migration_gaps',
  'v_migrated_projects',
  'v_complete_migration_status',
  'v_all_migrated_activities',
  'v_complete_sponsorships',
  'parties',
  'party_roles',
  'digital_entitlements',
  'third_party_claims',
  'third_party_settlements',
  'consortium_members',
  'entities',
  'legacy_reports',
  'legacy_report_details',
  'v_legacy_report',
  'resource_allocations',
  'e_invoices',
  'field_devices',
  'v_codes_full',
  'hr_leaves',
  'hr_salaries',
  'hr_delegates',
  'v_hr_personnel',
  'v_hr_salaries_summary',
  'v_hr_staff_complete',
  'v_hr_delegates_complete',
  'v_programs_sponsorships',
  'hr_staff',
  'hr_performance_evaluations',
  'sponsorship_payments',
  'hr_training',
  'hr_training_attendance',
  'v_sponsorships_programs',
  'v_sponsorships_beneficiaries',
  'v_sponsorships_parties',
  'sponsorships',
  'beneficiaries',
  'programs',
  'v_programs_detailed',
  'v_sponsorships_classified',
  'v_beneficiaries_detailed',
  'program_evaluations',
  'program_objectives',
  'kpi_indicators',
  'coding_system',
  'account_permissions',
  'cost_centers_advanced',
  'approval_thresholds',
  'account_restrictions',
  'account_entity_links',
  'v_endowment_projects',
  'v_endowment_transactions',
  'budget_lines',
  'activities',
  'control_reviews',
  'projects',
  'v_endowment_program_summary',
  'project_schedules',
  'milestones',
  'transactions',
  'guarantors',
  'v_program_dashboard_new',
  'v_project_dashboard_new',
  'project_tasks',
  'earned_value_metrics',
  'dependency_network',
  'v_donations_by_intermediary',
  'v_donor_intermediary_summary',
  'v_intermediary_performance',
  'v_statistical_summary_new',
  'v_project_performance_new',
  'v_beneficiaries_detailed_new',
  'v_budget_utilization_new',
  'v_activity_effectiveness_new',
  'v_activity_hierarchy_new',
  'v_activity_beneficiaries_full_new',
  'v_financial_transactions_detailed_new',
  'v_activity_dashboard_new',
  'v_program_performance_new',
  'v_activity_volunteers_full_new',
  'v_activity_attendance_full_new',
  'donations',
  'volunteers',
  'admin_users',
  'messages',
  'contacts',
  'subscribers',
  'notifications',
  'donation_approvals',
  'request_approvals',
  'movements',
  'fixed_assets',
  'transaction_lines',
  'contracts',
  'knowledge_articles',
  'strategic_plans',
  'strategic_goals',
  'strategic_kpis',
  'exchange_rates',
  'warehouses',
  'inventory_items',
  'grants',
  'donors',
  'procurement_tenders',
  'geographic_areas',
  'sales_invoices',
  'service_points',
  'v_nexora_realtime_domain_stats',
  // NEB-08: Partnership & Funding OS
  'grant_installments',
  'funding_proposals',
  'donor_reports',
  'partner_agreements',
  'donor_compliance_requirements',
  // NEB-06: Service Delivery OS
  'service_deliveries',
  'aid_distributions',
  'distribution_beneficiaries',
  // NEB-07: Community & Membership OS
  'volunteer_tasks',
  'community_committees',
  'membership_applications',
  // NEB-12: Integration OS
  'webhook_subscriptions',
  'iati_activities',
  'sync_queue',
  'api_rate_limits',
  // NEB-13: AI Intelligence OS
  'ai_insights',
  'chs_evaluations',
  'sphere_benchmarks',
  'anomaly_logs',
  'ai_model_runs',
  // NEB-14: Procurement OS
  'rfqs',
  'vendor_bids',
  'purchase_orders',
  'vendors',
  'three_way_match_records',
  // NEB-15: Fundraising
  'donation_campaigns',
  // New Views
  'v_grant_utilization_report',
  'v_donor_portfolio_analysis',
  'v_procurement_3way_match',
  'v_volunteer_hours_report',
  'v_service_delivery_metrics',
  'v_chs_compliance_dashboard',
  'v_beneficiary_vulnerability_index',
  'v_kpi_vs_target_dashboard',
  'v_ai_anomaly_detection_feed',
  'v_procurement_performance',
];

export function isWhitelisted(table: string): boolean {
  return TABLE_WHITELIST.includes(table) || table.startsWith('v_') || table.startsWith('vw_');
}

export const TABLE_POLICY_DOMAIN: Record<string, string> = {
  transactions: 'finance',
  transaction_lines: 'finance',
  chart_of_accounts: 'finance',
  journal_entries: 'finance',
  bank_accounts: 'finance',
  financial_closings: 'finance',
  currencies: 'finance',
  exchange_rates: 'finance',
  activities: 'activities',
  activity_tasks: 'activities',
  service_deliveries: 'activities',
  volunteers: 'activities',
  volunteer_tasks: 'activities',
  beneficiaries: 'beneficiaries',
  beneficiary_registrations: 'beneficiaries',
  projects: 'projects',
  programs: 'projects',
  project_schedules: 'projects',
  milestones: 'projects',
  sponsorships: 'sponsorships',
  sponsorship_installments: 'sponsorships',
  disbursements: 'disbursements',
  donors: 'donors',
  grants: 'donors',
  grant_installments: 'donors',
  proposals: 'donors',
  donor_reports: 'donors',
  partner_agreements: 'donors',
  purchase_orders: 'procurement',
  rfqs: 'procurement',
  rfq_bids: 'procurement',
  vendors: 'procurement',
  hr_staff: 'hr',
  attendance: 'hr',
  leave_requests: 'hr',
  performance_appraisals: 'hr',
  inventory_items: 'procurement',
  stock_movements: 'procurement',
  audit_logs: 'audit',
  approval_history: 'audit',
  approval_requests: 'audit',
  strategic_goals: 'projects',
  swot_entries: 'projects',
};
