export interface WorkspaceDefinition {
  id: string;
  code: string; // NEB-01 through NEB-15
  titleAr: string;
  titleEn: string;
  descriptionAr: string;
  descriptionEn: string;
  icon: string;
  viewId: string;
  requiredPermission: string;
  tenantScoped: boolean;
  branchScoped: boolean;
  fiscalScoped: boolean;
  status: 'ACTIVE' | 'BETA' | 'PLANNED';
  capabilities: string[];
  category: 'STRATEGY' | 'OPERATIONS' | 'FINANCE' | 'GOVERNANCE' | 'ENGAGEMENT';
}

export const WORKSPACE_REGISTRY: WorkspaceDefinition[] = [
  {
    id: 'ws-neb-01',
    code: 'NEB-01',
    titleAr: 'نظام إدارة الاستراتيجية والأداء المؤسسي',
    titleEn: 'Strategy & Performance OS',
    descriptionAr: 'التخطيط الاستراتيجي الخماسي، الأهداف العلوية، مؤشرات KPI والبطاقات المتوازنة',
    descriptionEn: '5-Year Strategic Planning, OKRs, KPIs & Balanced Scorecards',
    icon: 'Target',
    viewId: 'strategy',
    requiredPermission: 'strategy.read',
    tenantScoped: true,
    branchScoped: false,
    fiscalScoped: true,
    status: 'ACTIVE',
    capabilities: ['Strategic Plans', 'SWOT Analysis', 'KPI Tracker', 'Balanced Scorecard', 'Initiatives'],
    category: 'STRATEGY',
  },
  {
    id: 'ws-neb-02',
    code: 'NEB-02',
    titleAr: 'نظام إدارة محافظ البرامج والمشاريع',
    titleEn: 'Portfolio Management OS',
    descriptionAr: 'تحليل الميزانيات التجميعية، استثمار الأوقاف، ومصفوفة المخاطر والمكاسب',
    descriptionEn: 'Consolidated Budgeting, Endowment Investments & Risk-Return Analysis',
    icon: 'Briefcase',
    viewId: 'portfolio',
    requiredPermission: 'portfolio.read',
    tenantScoped: true,
    branchScoped: true,
    fiscalScoped: true,
    status: 'ACTIVE',
    capabilities: ['Portfolio Analytics', 'Endowment Investments', 'Returns Tracking', 'Strategic Alignment'],
    category: 'STRATEGY',
  },
  {
    id: 'ws-neb-03',
    code: 'NEB-03',
    titleAr: 'نظام إدارة البرامج التنموية والإنسانية',
    titleEn: 'Program Management OS',
    descriptionAr: 'إدارة محاور التدخل، ميزانيات البرامج، وقياس الأثر الاستراتيجي',
    descriptionEn: 'Intervention Pillars, Program Budgets & Impact Assessment',
    icon: 'Layers',
    viewId: 'programs',
    requiredPermission: 'programs.read',
    tenantScoped: true,
    branchScoped: true,
    fiscalScoped: true,
    status: 'ACTIVE',
    capabilities: ['Program Lifecycle', 'Budget Allocation', 'Target Beneficiaries', 'Program KPIs'],
    category: 'OPERATIONS',
  },
  {
    id: 'ws-neb-04',
    code: 'NEB-04',
    titleAr: 'نظام إدارة المشاريع الميدانية والتنفيذ',
    titleEn: 'Project Management OS',
    descriptionAr: 'متابعة المشاريع الميدانية، مراحل التنفيذ، القيمة المكتسبة Earned Value وتدفقات الصرف',
    descriptionEn: 'Field Projects, Milestones, Earned Value Management & Cashflows',
    icon: 'FolderKanban',
    viewId: 'projects',
    requiredPermission: 'projects.read',
    tenantScoped: true,
    branchScoped: true,
    fiscalScoped: true,
    status: 'ACTIVE',
    capabilities: ['Project Charters', 'WBS Breakdown', 'Milestones', 'Risk Logs', 'Gantt Charting'],
    category: 'OPERATIONS',
  },
  {
    id: 'ws-neb-05',
    code: 'NEB-05',
    titleAr: 'نظام إدارة العمليات الميدانية والمهام WBS',
    titleEn: 'Operations & Field Execution OS',
    descriptionAr: 'إسناد المهام الميدانية، الأدلة الثبوتية بالصور، والرفع الجغرافي GIS',
    descriptionEn: 'Field Task Allocation, Photo Evidence & GIS Location Mapping',
    icon: 'CheckSquare',
    viewId: 'tasks',
    requiredPermission: 'tasks.read',
    tenantScoped: true,
    branchScoped: true,
    fiscalScoped: false,
    status: 'ACTIVE',
    capabilities: ['Task Dispatch', 'GPS Proof of Work', 'Field Logs', 'Quality Audits'],
    category: 'OPERATIONS',
  },
  {
    id: 'ws-neb-06',
    code: 'NEB-06',
    titleAr: 'نظام خدمة المستفيدين والكفالات',
    titleEn: 'Service Delivery & Beneficiaries OS',
    descriptionAr: 'السجل الموحد للمستفيدين، تقييم الاحتياج، وصرف الكفالات والمساعدات',
    descriptionEn: 'Unified Beneficiary Registry, Need Assessment & Sponsorship Disbursal',
    icon: 'Users',
    viewId: 'beneficiaries',
    requiredPermission: 'beneficiaries.read',
    tenantScoped: true,
    branchScoped: true,
    fiscalScoped: true,
    status: 'ACTIVE',
    capabilities: ['Beneficiary Profiles', 'Need Scoring', 'Sponsorship Engine', 'Distribution Vouchers'],
    category: 'OPERATIONS',
  },
  {
    id: 'ws-neb-07',
    code: 'NEB-07',
    titleAr: 'نظام العمل التطوعي والأعضاء',
    titleEn: 'Community & Volunteer OS',
    descriptionAr: 'استقطاب المتطوعين، احتساب الساعات التطوعية، وسجلات الأعضاء',
    descriptionEn: 'Volunteer Recruitment, Hours Ledger & Membership Registry',
    icon: 'UserCheck',
    viewId: 'volunteers',
    requiredPermission: 'volunteers.read',
    tenantScoped: true,
    branchScoped: true,
    fiscalScoped: true,
    status: 'ACTIVE',
    capabilities: ['Volunteer Roster', 'Hours Calculation', 'Skill Matching', 'Certificates'],
    category: 'ENGAGEMENT',
  },
  {
    id: 'ws-neb-08',
    code: 'NEB-08',
    titleAr: 'نظام الشراكات والتمويل والمانحين',
    titleEn: 'Partnerships & Donor Grants OS',
    descriptionAr: 'سجل المانحين والشركاء، اتفاقيات التمويل، القيود والمخصصات والتقارير المالية للجهات',
    descriptionEn: 'Donor Registry, Grant Agreements, Earmarked Funding & IATI Reporting',
    icon: 'Handshake',
    viewId: 'partnerships',
    requiredPermission: 'partnerships.read',
    tenantScoped: true,
    branchScoped: false,
    fiscalScoped: true,
    status: 'ACTIVE',
    capabilities: ['Donor Agreements', 'Grant Restrictions', 'IATI Compliance', 'Installments Tracker'],
    category: 'ENGAGEMENT',
  },
  {
    id: 'ws-neb-09',
    code: 'NEB-09',
    titleAr: 'نظام إدارة الأصول والموارد البشرية',
    titleEn: 'Resource & Asset OS',
    descriptionAr: 'الأصول الثابتة، الإهلاك الآلي، الهيكل التنفيذي للكوادر والمسيرات',
    descriptionEn: 'Fixed Assets, Auto Depreciation, HR Roster & Payroll Processing',
    icon: 'Building2',
    viewId: 'assets',
    requiredPermission: 'assets.read',
    tenantScoped: true,
    branchScoped: true,
    fiscalScoped: true,
    status: 'ACTIVE',
    capabilities: ['Fixed Assets Register', 'Depreciation Run', 'Custodian Tracking', 'HR Personnel'],
    category: 'FINANCE',
  },
  {
    id: 'ws-neb-10',
    code: 'NEB-10',
    titleAr: 'نظام المالية المحاسبية والامتثال IPSAS',
    titleEn: 'Finance & IPSAS Compliance OS',
    descriptionAr: 'شجرة الحسابات الموحدة، القيود المحاسبية، القوائم المالية والتحقق بالذكاء الاصطناعي',
    descriptionEn: 'Unified Chart of Accounts, Journal Entries, IPSAS Reporting & AI Audit',
    icon: 'Calculator',
    viewId: 'financials',
    requiredPermission: 'finance.read',
    tenantScoped: true,
    branchScoped: true,
    fiscalScoped: true,
    status: 'ACTIVE',
    capabilities: ['Chart of Accounts', 'Journal Entries', 'Trial Balance', 'IPSAS Statements', 'Budget Control'],
    category: 'FINANCE',
  },
  {
    id: 'ws-neb-11',
    code: 'NEB-11',
    titleAr: 'نظام إدارة المعرفة والأرشيف والسياسات',
    titleEn: 'Knowledge & Policy OS',
    descriptionAr: 'الأرشيف الإلكتروني، المستندات الموقعة، الدلائل التشغيلية والسياسات',
    descriptionEn: 'Document Management, Digital Archive, SOPs & Governance Policies',
    icon: 'BookOpen',
    viewId: 'knowledge',
    requiredPermission: 'knowledge.read',
    tenantScoped: true,
    branchScoped: false,
    fiscalScoped: false,
    status: 'ACTIVE',
    capabilities: ['Document Archive', 'Version Control', 'Policy Library', 'Access Controls'],
    category: 'GOVERNANCE',
  },
  {
    id: 'ws-neb-12',
    code: 'NEB-12',
    titleAr: 'نظام التكامل والربط الرقمي',
    titleEn: 'Digital Integration & Neon OS',
    descriptionAr: 'ربط قاعدة بيانات Neon PostgreSQL، مفاتيح API، والويبهوكس وتراخيص البوابة',
    descriptionEn: 'Neon PostgreSQL Integration, API Keys, Webhooks & Connectivity Status',
    icon: 'Cpu',
    viewId: 'integration',
    requiredPermission: 'admin.manage',
    tenantScoped: true,
    branchScoped: false,
    fiscalScoped: false,
    status: 'ACTIVE',
    capabilities: ['Neon Database Engine', 'REST APIs', 'Webhook Execution', 'Audit Logs'],
    category: 'GOVERNANCE',
  },
  {
    id: 'ws-neb-13',
    code: 'NEB-13',
    titleAr: 'نظام الذكاء الاصطناعي وتقييم الأثر Sphere/CHS',
    titleEn: 'AI Intelligence & Impact OS',
    descriptionAr: 'تحليلات Gemini AI المتقدمة، قياس الأثر المعياري الميداني وفق Sphere & CHS',
    descriptionEn: 'Gemini AI Enterprise Insights & Sphere/CHS Humanitarian Impact Metrics',
    icon: 'Sparkles',
    viewId: 'ai_analytics',
    requiredPermission: 'ai.access',
    tenantScoped: true,
    branchScoped: true,
    fiscalScoped: true,
    status: 'ACTIVE',
    capabilities: ['Gemini Smart Assistant', 'Sphere Compliance', 'CHS Quality Standards', 'Predictive Impact'],
    category: 'STRATEGY',
  },
  {
    id: 'ws-neb-14',
    code: 'NEB-14',
    titleAr: 'نظام المشتريات والمناقصات والتوريد',
    titleEn: 'Procurement & Tenders OS',
    descriptionAr: 'طلبات الشراء، المناقصات، أوامر التوريد، وتقييم الموردين',
    descriptionEn: 'Purchase Requisitions, Tenders, Vendor Management & POs',
    icon: 'ShoppingCart',
    viewId: 'procurement',
    requiredPermission: 'procurement.read',
    tenantScoped: true,
    branchScoped: true,
    fiscalScoped: true,
    status: 'ACTIVE',
    capabilities: ['Purchase Requisitions', 'Vendor Registry', 'RFQ Tenders', 'Purchase Orders'],
    category: 'FINANCE',
  },
  {
    id: 'ws-neb-15',
    code: 'NEB-15',
    titleAr: 'نظام التبرعات والإيرادات والمبيعات',
    titleEn: 'Sales, Revenue & Fundraising OS',
    descriptionAr: 'حملات التبرع، السندات الرقمية، إيرادات الأوقاف، وفواتير الاستثمار',
    descriptionEn: 'Donation Campaigns, E-Receipts, Endowment Revenue & Invoicing',
    icon: 'DollarSign',
    viewId: 'fundraising',
    requiredPermission: 'fundraising.read',
    tenantScoped: true,
    branchScoped: true,
    fiscalScoped: true,
    status: 'ACTIVE',
    capabilities: ['Donation Receipts', 'Campaign Management', 'Revenue Ledger', 'Donor Invoicing'],
    category: 'ENGAGEMENT',
  },
];

export function getWorkspaceByCode(code: string): WorkspaceDefinition | undefined {
  return WORKSPACE_REGISTRY.find(w => w.code.toLowerCase() === code.toLowerCase());
}

export function getWorkspaceByViewId(viewId: string): WorkspaceDefinition | undefined {
  return WORKSPACE_REGISTRY.find(w => w.viewId.toLowerCase() === viewId.toLowerCase());
}
